language: csharp
os:
  - linux
  - osx

sudo: required
dist: trusty

# See also https://github.com/dotnet/core/blob/master/Documentation/prereqs.md
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

mono:
  - latest

osx_image: xcode7.3

install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install openssl; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew list; fi

script:
  - ./build.sh --target Travis --verbosity diagnostic
