language: csharp
os:
  - linux
  - osx

sudo: required
dist: trusty

mono:
  - 5.12.0
  - 5.20.1

dotnet: 3.1.101

# OS X 10.12
osx_image: xcode11.2

before_install:
  - git fetch --unshallow # Travis always does a shallow clone, but GitVersion needs the full history including branches and tags
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  - git fetch origin

script:
  - ./build.sh --target=Travis --verbosity=diagnostic
