environment:
  deployment_api_key:
    secure: EOVLFyiHRhh9Jij3/mITdSV5JH1SzT8JUbqqTIFtvOPndNeMme3mME01ws3+5nFB

init:
  - git config --global core.autocrlf input

build_script:
  - ps: .\build.ps1 -target AppVeyor -verbosity diagnostic

test: off

deploy: off
