init:
  - git config --global core.autocrlf input

build_script:
  - ps: .\build.ps1

test: off

artifacts:
- path: artifacts\*.nupkg
  name: Packages

deploy:
- provider: NuGet
  server: https://www.myget.org/F/maxfire/api/v2/package
  api_key:
    secure: EOVLFyiHRhh9Jij3/mITdSV5JH1SzT8JUbqqTIFtvOPndNeMme3mME01ws3+5nFB
  skip_symbols: true
  artifact: Packages
